# Base image
FROM node:20.15.1-alpine3.20

# Create app directory
WORKDIR /usr/src/app

COPY package.json yarn.lock ./

# Install app dependencies
RUN yarn install

# Bundle app source
COPY . .

# Set default ports via environment variables (optional)
ENV APP_PORT=3004
ENV DEBUG_PORT=9231

# Expose both the main and debug ports using the environment variables
EXPOSE ${APP_PORT}
EXPOSE ${DEBUG_PORT}

CMD ["yarn", "start:local:docker:watch:debug"]
