# Base image
FROM node:20.15.1-alpine3.20

# Create app directory
WORKDIR /usr/src/app

# Bundle app source
COPY . .

COPY yarn.lock ./

# Install app dependencies
RUN yarn install

# Creates a "dist" folder with the production build
RUN yarn build-develop

# Expose the port on which the app will run
EXPOSE 3002

COPY start-dev.sh /usr/src/app/
RUN chmod +x /usr/src/app/start-dev.sh
CMD ["/usr/src/app/start-dev.sh"]
