# Base image
FROM node:20.15.1-alpine3.20

# Create app directory
WORKDIR /usr/src/app

COPY package.json yarn.lock ./

# Install app dependencies
RUN yarn install

# Bundle app source
COPY . .

# Expose both the main and debug ports using the environment variables
EXPOSE $APP_PORT
EXPOSE $DEBUG_PORT

CMD ["sh", "-c", "yarn prisma:local:docker:generate && yarn start:local:docker:watch:debug"]
