# Base image
FROM node:20.15.1-alpine3.20

# Create app directory
WORKDIR /usr/src/app

# Bundle app source
COPY . .

COPY yarn.lock ./

# Install app dependencies
RUN yarn install

# Creates a "dist" folder with the production build
RUN yarn build-local

# Expose the port on which the app will run
EXPOSE 3002 9290

CMD ["yarn", "start:local:debug"]
