export enum ErrorCodes {
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  USER_ALREADY_EXISTS = 'USER_ALREADY_EXISTS',
  UNAUTHORIZED = 'UNAUTHORIZED',

  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',

  INVALID_REFRESH_TOKEN = 'INVALID_REFRESH_TOKEN',
  MISSING_REFRESH_TOKEN = 'MISSING_REFRESH_TOKEN',

  INVALID_TOKEN = 'INVALID_TOKEN',
  MISSING_TOKEN = 'MISSING_TOKEN',

  PASSWORD_NOT_FOUND = 'PASSWORD_NOT_FOUND',
  PASSWORD_CANNOT_BE_EMPTY = 'PASSWORD_CANNOT_BE_EMPTY',
}
