name: Deploy NestJS Microservice to AWS ECS
on:
  push:
    branches: [develop, main]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
          cache: 'yarn'

      - name: Run Yarn Install
        run: |
          npm i -g corepack
          yarn install

      - name: Run build
        run: yarn build-develop

      - name: Upload application
        uses: actions/upload-artifact@v4
        with:
          name: app-artifact-dev
          path: dist/
          retention-days: 3

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.DAVIDECARETOKEN }}
        run: npx semantic-release

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: 'eu-central-1'

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2
        with:
          registry-id: ${{ secrets.AWS_ACCOUNT_ID }}

      - name: Build, tag, and push image to Amazon ECR
        run: |
          docker build -t $ECR_REPOSITORY:$IMAGE_TAG -f Dockerfile.dev .
          docker push $ECR_REPOSITORY:$IMAGE_TAG
        env:
          ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
          IMAGE_TAG: ${{ github.sha }}

      - name: Amazon ECS "Deploy Task Definition" Action for GitHub Actions
        uses: aws-actions/amazon-ecs-deploy-task-definition@v2.0.0
        with:
          task-definition: ProdBoilerplateNestjs
          service: ProdBoilerplateNestjs
          cluster: ProdBoilerplateNestjs
        env:
          ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
          IMAGE_TAG: ${{ github.sha }}
