name: Deploy NestJS Microservice to AWS ECS
on:
  push:
    branches: [develop, main]
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: 'eu-central-1'

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2
        with:
          registry-id: ${{ secrets.AWS_ACCOUNT_ID }}

      - name: Build, tag, and push image to Amazon ECR
        run: |
          docker build -t $ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REPOSITORY:$IMAGE_TAG
        env:
          ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
          IMAGE_TAG: ${{ github.sha }}

      - name: Amazon ECS "Deploy Task Definition" Action for GitHub Actions
        uses: aws-actions/amazon-ecs-deploy-task-definition@v2.0.0
        with:
          task-definition: ProdBoilerplateNestjs
          container-name: ProdBoilerplateNestjs
          image: $ECR_REPOSITORY:$IMAGE_TAG
          service: boilerplate-nestjs-service
          cluster: ProdBoilerplateNestjs
        env:
          ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
          IMAGE_TAG: ${{ github.sha }}
